Standardize pathways
trias-project/alien-macroinvertebrates pull request #31
Opened 2017-12-22 14:20 UTC by LienReyserhove

I updated the vocabulary of `pathway` in the dataset as suggested in the [updated vocabulary](https://github.com/trias-project/vocab/blob/master/vocabulary/pathway.tsv).

I'm not 100% sure whether this suggested vocabulary covers all terms, e.g.:

|pathway                   |suggested vocabulary |
|:-------------------------|:--------------------|
|aquaculture               |escape_aquaculture   |
|escape_aquaculture        |mariculture          |
|Aquaculture / mariculture |escape_aquaculture   |

Now, there's no distinction between aquaculture and mariculture here, while they do make the distinction in the [CBD standard](https://www.cbd.int/doc/meetings/sbstta/sbstta-18/official/sbstta-18-09-add1-en.pdf). For me, this is a loss of information... Or am I wrong?

2017-12-22 15:08 UTC, peterdesmet requested changes
1. The CBD vocab does *not* make a distinction between aquaculture and mariculture: it's listed in one term. Although this is a slight loss of information, we'll stick to the vocab rather than inventing our own terms
2. `stowaway_transport` should be `stowaway_other`
3. Can you add a bit more text before the mapping, at least referencing the vocab we're using (https://github.com/trias-project/vocab/tree/master/vocabulary/pathway)?
4. Prepend codes with `cbd_2014_pathway:`

Thanks!

2018-01-03 09:21 UTC, peterdesmet commented
Idem to https://github.com/trias-project/alien-plants-belgium/pull/55#issuecomment-354960621 maybe use a `paste()` to add `cbd_2014_pathway` to the non-empty values. Seems more robust.

2018-01-09 08:54 UTC, LienReyserhove commented
The requested changes are integrated and the file is ready for review.
Remark: these files contain the old way to generate `taxonID`. I will generate a new `taxonID `based on a hash (see [issue 44](https://github.com/trias-project/alien-plants-belgium/issues/44) in alien-plants-belgium), but I will generate a new brach for this.

2018-01-09 10:39 UTC, peterdesmet approved these changes

2018-01-09 10:39 UTC, merged